### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by trhumphries** [devkanro/setup-statusfy-demo#5]
An Azure outage is effecting our servers

**Comment by devkanro** [comment]
There are some preconditions to create an incident issue.

## Precondition of creating an incident issue
1. You must be the 'COLLABORATOR', 'MEMBER' or 'OWNER' of the repository
2. The issue must contain one severity label and at least one system label

If you want to try creating your own incident issue, you can create a repository from this template repository.
The `Use this template` button is at the right of the clone code button on the homepage of this repository.

Or if you just want to try the workflow of `setup-statusfy`, I can invite you as the repository member.
